### ISSUE TITLE
Support windows - Windows tests won't build

### ISSUE THREAD

**Issue by nrbnlulu** [qtgql/qtgql#227]
For some reason windows can't compile well on any architecture I tried. You can see the output in the CI.

**Comment by nrbnlulu** [comment]
Seems like it is related to catch2 since without linking to catch2 I could build just the core target.

**Comment by omortie** [comment]
there are also some problems with windows-specific path (with backslashes) generated in tests/test_codegen/generated_test_projects/CMakeLists.txt, I'm trying to fix it

**Comment by nrbnlulu** [comment]
:+1:

**Comment by nrbnlulu** [comment]
I think it is here
https://github.com/qtgql/qtgql/blob/a255495f906176140a6f8bbd6987048b5416bfa0/tests/test_codegen/testcases.py#L122

**Comment by omortie** [comment]
yes I've fixed this, but there is also another issue with long filename path in windows, I'm on it
