### ISSUE TITLE
Migrate to conan instead of aqt-install

### ISSUE THREAD

**Issue by nrbnlulu** [qtgql/qtgql#262]
new conan v2 Qt6 was merged we can migrate to use it. https://github.com/conan-io/conan-center-index/pull/17539#event-9505668295

**Comment by omortie** [comment]
WIP here: https://github.com/omortie/qtgql/tree/WIP-262-Migrate-to-conan-instead-of-aqt-install

there is still a problem with building tests here: `tests/test_codegen/generated_test_projects/ScalarsTestCase/graphql/__generated__/CMakeLists.txt:27 (qt_policy)`
that says:
`QTP0001 is not a known Qt policy.  Did you include the necessary Qt module?`

also I've used this code to install and build with conan: 
```
export NOT_ON_C3I=1
poetry run conan build . -o test=True --build=missing
```

**Comment by omortie** [comment]
it seems it needs to also bind to qtdeclarative and qtquickcontrols as described here: https://stackoverflow.com/a/67615177/9751735

**Comment by nrbnlulu** [comment]
build times with conan takes decades. we're unlikely to support that. users ought to supply Qt themselfes...
